name: api-dings main

on:
  push:
    branches:
      - main
    paths:
      - 'api-dings/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

defaults:
  run:
    working-directory: ./api-dings

jobs:
  build:
    name: Build and push Docker container
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: 14

      - name: Setup build cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Run tests
        run: ./gradlew clean test
      - name: Build with Gradle
        run: ./gradlew shadowJar -x test

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build an push the Docker image
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev-gcp:
    name: Deploy to dev-gcp
    needs: build
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/gcp/naiserator-gcp.yml
          VARS: .nais/gcp/dev-gcp-vars.yml

  deploy-prod-gcp:
    name: Deploy to prod-gcp
    needs: build
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/gcp/naiserator-gcp.yml
          VARS: .nais/gcp/prod-gcp-vars.yml

  deploy-dev-onprem:
    name: Deploy to dev-onprem
    needs: build
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/fss/naiserator-fss.yml
          VARS: .nais/fss/dev-fss-vars.yml

  deploy-prod-onprem:
    name: Deploy to prod-onprem
    needs: build
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/fss/naiserator-fss.yml
          VARS: .nais/fss/prod-fss-vars.yml
