name: quotes-analytics

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/quotes-analytics.yaml
      - .github/workflows/service-pipeline.yaml
      - quotes-analytics/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/quotes-analytics.yaml
      - .github/workflows/service-pipeline.yaml
      - quotes-analytics/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/service-pipeline.yaml
    with:
      service-name: quotes-analytics
      service-path: ./quotes-analytics
      enable-tests: true
      enable-coverage: true
      coverage-flag: quotes-analytics
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
